### ISSUE TITLE
Update to JSON-Schema v6

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/wetzel#13]
Contributions are very welcome for this one!

See https://github.com/KhronosGroup/glTF/issues/929

**Comment by paulmeems-waterwatchfoundation** [comment]
Any progress on this?
I just stumbled on the tool and it seems the right tool for what I need: document my json schema without having two sources of content.
But my schema is based on `draft-07`

**Comment by pjcozzi** [comment]
@paulmeems-waterwatchfoundation I'm not aware of anyone working on this, but the contribution would be welcome if you want to make the changes.  We may still need to keep a branch for the older JSON schema until glTF updates, https://github.com/KhronosGroup/glTF/issues/929

**Comment by Relequestual** [comment]
I've been trying to do a little work with Adobe on their version of a similar tool, https://github.com/adobe/jsonschema2md
It's much more up to date, supporting draft-7.

There's still a lot to be done to make it ready for general use, but if anyone is looking to put in work to have a JSON Schema to markdown tool, I'd look there rather than here, probably.

**Comment by pjcozzi** [comment]
@Relequestual we looked briefly at the Adobe tool and would consider using it for the glTF spec - which is what we originally wrote wetzel for - but I think it still needs more work before we could do so.  @javagl will know the specifics.

**Comment by javagl** [comment]
@Relequestual  This was recently addressed, to some extent, in https://github.com/KhronosGroup/glTF/issues/1607 

As mentioned there, I gave jsonschema2md a quick try, but have to investigate it further. The current documentation that is generated by wetzel is rather sophisticated, and we'll still have to figure out whether jsonschema2md can come close enough to this.

Currently, wetzel is *somewhat* hand-tailored for glTF (because that was its primary use case), and so the schema version of the glTF spec and wetzel should (or rather: have to) match.

**Comment by emackey** [comment]
OBE, see #59.

**Comment by Relequestual** [comment]
@emackey Nice work in resolving this issue!

It would be great if you could declare your version support in your readme, and update the example in the readme too.

After doing so, we would be able to accept a PR to list the project here https://json-schema.org/implementations.html#documentation-generators
