### ISSUE TITLE
Fix links in generated markdown

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/wetzel#21]
See https://github.com/KhronosGroup/glTF/pull/1008/files

**Comment by HowardWolosky** [comment]
The main issue here is that the generated documentation being referenced had the incorrect typing for the filename in the root schema.  This was due to the way that the user had cased the file on input to Wetzel (and could also be impacted by the casing of the filename authored in the `$ref` field within an individual schema). So, to make Wetzel robust to user input, Wetzel should get the file from disk and grab the casing from the file on disk as opposed to directly taking the user/schema input.

**Comment by emackey** [comment]
Seems fixed now.
